name: CI - Next.js Frontend

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Instalar dependencias
        run: npm install

      - name: Ejecutar Linter (ESLint)
        run: |
          npm run lint || echo "Lint tuvo errores, pero no fallamos el build."

      # - name: Ejecutar Tests (si tenés)
      #   run: npm test

      - name: Build del proyecto
        run: npm run build
